// Engine integration, not authenticated UI E2E. Real downloaded models; no stubs.
import { chromium } from 'playwright';
import { readFile, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const context = await chromium.launchPersistentContext('/browser-profile', { headless: true, viewport: { width: 390, height: 844 } });
const page = await context.newPage();
const requests = [];
page.on('request', r => requests.push({ method: r.method(), url: r.url() }));
page.on('pageerror', e => console.log('pageerror:', e.message));
try {
  await page.goto(process.env.TEST_ORIGIN || 'http://127.0.0.1:3000');
  // Match the real Send gesture; do not bypass browser autoplay policy.
  await page.getByRole('button', { name: 'Conversation options', exact: true }).click();
  await page.evaluate(() => {
    window.localReviewEvents = [];
    window.localReviewWorker = new Worker('/local-worker.js', { type: 'module' });
    window.localReviewWorker.onmessage = ({ data }) => window.localReviewEvents.push(data);
    window.localReviewWorker.onerror = e => window.localReviewEvents.push({ type: 'error', message: e.message });
    window.localReviewWorker.postMessage({ type: 'load' });
  });
  const start = Date.now();
  for (let i = 0; i < 240; i++) {
    const status = await page.evaluate(() => window.localReviewEvents.at(-1));
    console.log(JSON.stringify({ seconds: Math.round((Date.now() - start) / 1000), status }));
    if (status?.type === 'error') throw new Error(status.message);
    if (status?.type === 'ready') break;
    assert.ok(i < 239, 'Model loading timed out');
    await page.waitForTimeout(5000);
  }
  const loadingMs = Date.now() - start;
  const fixture = (await readFile('/evidence/synthetic-note.wav')).toString('base64');
  await context.setOffline(true);
  console.log('Models loaded; network now offline. Starting actual voice turn.');
  const boundary = requests.length;
  await page.evaluate(async encoded => {
    const context = new AudioContext();
    const decoded = await context.decodeAudioData(Uint8Array.from(atob(encoded), c => c.charCodeAt(0)).buffer);
    const offline = new OfflineAudioContext(1, Math.ceil(decoded.duration * 16000), 16000);
    const source = offline.createBufferSource(); source.buffer = decoded; source.connect(offline.destination); source.start();
    const samples = (await offline.startRendering()).getChannelData(0);
    await context.close();
    window.localReviewWorker.postMessage({ type: 'turn', samples: samples.buffer, history: [] }, [samples.buffer]);
  }, fixture);
  await page.waitForFunction(() => window.localReviewEvents.some(x => x.type === 'reply' || x.type === 'error'), undefined, { timeout: 240000 });
  console.log('Voice turn returned; checking full speech playback.');
  const result = await page.evaluate(async () => {
    const reply = window.localReviewEvents.find(x => x.type === 'reply' || x.type === 'error');
    if (reply.type === 'error') throw new Error(reply.message);
    if (!reply.samples?.length) throw new Error(reply.warning || 'No synthesized audio');
    // Decode/play the actual PCM generated by the speech model via Web Audio.
    const context = new AudioContext(); await context.resume();
    const buffer = context.createBuffer(1, reply.samples.length, reply.rate); buffer.copyToChannel(reply.samples, 0);
    const source = context.createBufferSource(); source.buffer = buffer; source.connect(context.destination);
    const ended = new Promise(resolve => { source.onended = resolve; }); source.start(); await ended;
    const duration = buffer.duration; await context.close();
    return { transcript: reply.transcript, reply: reply.text, duration, samples: reply.samples.length, rate: reply.rate };
  });
  assert.match(result.transcript.toLowerCase(), /quiet/);
  assert.ok(result.duration > 0 && result.reply.length > 0);
  console.log(JSON.stringify({ inferenceRequests: requests.slice(boundary) }));
  assert.equal(requests.slice(boundary).length, 0, 'Inference attempted a network request');
  assert.equal(requests.some(x => x.url.includes('/api/turn') || x.method === 'POST'), false);
  const receipt = { passed: true, scope: 'Browser worker engine integration with actual weights and offline transcription, generation and full PCM playback; not Google-authenticated UI or physical microphone qualification', loadingMs, totalMs: Date.now() - start, offlineRequests: 0, ...result };
  await writeFile('/evidence/local-browser.json', JSON.stringify(receipt, null, 2));
  console.log(JSON.stringify(receipt));
} catch (error) {
  await writeFile('/evidence/local-browser-failure.json', JSON.stringify({ passed: false, message: error.message }, null, 2));
  throw error;
} finally { await context.close(); }
